"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const appPolicyController_1 = __importDefault(require("../controllers/appPolicyController"));
const appPolicyUseCases_1 = __importDefault(require("../../domain/usecases/appPolicyUseCases"));
const appPolicyRepoImpl_1 = __importDefault(require("../../infrastructure/database/repositories/appPolicyRepoImpl"));
const authMiddleware_1 = require("../middlewares/authMiddleware");
const user_roles_enum_1 = require("../../shared/constants/user-roles.enum");
const appPolicyValidator_1 = require("../validators/appPolicyValidator");
const appPolicyRouter = (0, express_1.Router)({ mergeParams: true });
const appPolicyController = new appPolicyController_1.default(new appPolicyUseCases_1.default({ appPolicyRepo: appPolicyRepoImpl_1.default }));
appPolicyRouter.get("/", authMiddleware_1.protect, appPolicyController.getAppPolicy);
appPolicyRouter.post("/:type", authMiddleware_1.protect, (0, authMiddleware_1.allowedTo)([user_roles_enum_1.UserRole.ADMIN]), appPolicyValidator_1.createAppPolicyValidator, appPolicyController.createAppPolicy);
appPolicyRouter.get("/:type", authMiddleware_1.protect, (0, authMiddleware_1.allowedTo)([user_roles_enum_1.UserRole.ADMIN]), appPolicyController.getAppPolicy);
appPolicyRouter.put("/:type", authMiddleware_1.protect, (0, authMiddleware_1.allowedTo)([user_roles_enum_1.UserRole.ADMIN]), appPolicyValidator_1.updateAppPolicyValidator, appPolicyController.updateAppPolicy);
// appPolicyRouter.delete("/:type", protect, allowedTo([UserRole.ADMIN]), appPolicyController.deleteAppPolicy);
exports.default = appPolicyRouter;
